# Generated by Django 4.1.5 on 2023-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Distance',
            field=models.FloatField(max_length=120),
        ),
        migrations.AlterField(
            model_name='show',
            name='height',
            field=models.FloatField(),
        ),
    ]
