# Generated by Django 4.1.5 on 2023-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_show_distance_alter_show_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference_show',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other(Both)'), ('Male', 'Male'), ('Female', 'Female')], default='NA', max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='show',
            name='education',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PHD', 'PHD'), ('Post Doctorate', 'Post Doctorate')], default='NA', max_length=120),
        ),
        migrations.AlterField(
            model_name='show',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other(Both)'), ('Male', 'Male'), ('Female', 'Female')], default='NA', max_length=6),
        ),
    ]
