# Generated by Django 4.1.5 on 2023-03-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_preference_show_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference_show',
            name='Language',
        ),
        migrations.AddField(
            model_name='preference_show',
            name='Language',
            field=models.ManyToManyField(max_length=120, to='accounts.demo'),
        ),
    ]
