# Generated by Django 4.1.5 on 2023-03-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_preference_show_language_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo',
            new_name='alllang',
        ),
    ]
