# Generated by Django 4.1.5 on 2023-03-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_demo_alllang'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference_show',
            name='Hobbies',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
