# Generated by Django 4.1.5 on 2023-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_preference_show_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='height',
            field=models.CharField(max_length=120),
        ),
    ]
