# Generated by Django 4.1.5 on 2023-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_show_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference_show',
            name='max_height',
            field=models.CharField(default=0, max_length=120, verbose_name='Max height'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference_show',
            name='min_height',
            field=models.CharField(default='0', max_length=120, verbose_name='Min height'),
            preserve_default=False,
        ),
    ]
