# Generated by Django 4.1.5 on 2023-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_preference_show_max_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference_show',
            name='max_age',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Max age in years'),
        ),
        migrations.AlterField(
            model_name='preference_show',
            name='min_age',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Min age in years'),
        ),
    ]
